---
baseurl: "https://galtelino.github.io"
date: "2016-12-09"
languageCode: "en-us"
title: "Gio Altelino"
theme: "material-design"
MetaDataFormat: "yaml"
paginate: "9"

params:
  description: "Programmer, mostly interested in high performance code"
  twitter: "@GioAltelino"
  github: "gAltelino"
  googleAnalyticsUserID: "UA-83972047-1"
  category: [ "Programming", "Hardware", "Databases", "Agile" ]
  tag: [ "C/C++", "Python", "Go", "UML", "SQL", "Parralel" ]

---
